require 'getoptlong'
# ruby -w Vagrantfile

# Which devices do we know about?
# - and check for their driver on the hosting host
# ioTypes = {
#
# }

def checkIoModule()
  ioModule=`lsmod | grep iomemory`
  if ioModule != ""
    return ioModule
  end
  return false
end

#
#
##
def checkVmStatus(boxParam)
  # bad idea, circular loop, make sure status does not call status?!
  status=`cat .vagrant/machines/default/libvirt/box_meta`
  if status != ""
    puts status
  else
    puts("Unable to retrieve status for #{boxParam}, updating box")
    `vagrant --box=#{boxParam} box update`
  end
end
##
# Check for io devices that we care about
##
def findBusIoDevices()
  busDeviceMap={}
  mString=' SanDisk'
  # rString='Mass storage controller [0180]: '
  # 05:00.0 Mass storage controller [0180]: SanDisk ioDimm3 [1aed:1005] (rev 01)
  # 06:00.0 Mass storage controller [0180]: SanDisk ioDimm3 [1aed:1005] (rev 01)
  # 08:00.0 Mass storage controller [0180]: SanDisk ioMemory HHHL [1aed:3002]
  ioDevices=`lspci -nn | grep #{mString}`.split(/\n+/)
  if ioDevices != ""
    for line in ioDevices
      # somehow the first character in bust is "", so we move some things around
      bust=line.split(/(\d{2}):([\d\.]+) ([\w\s]+) (\[\d+\]): ([\w\d\s]+) \[([\w\d]+):([\w\d]+)\]\s?(\(rev (\d+)?)?/)
      busDeviceMap[bust[1]] = {
        :pciId => "#{bust[1]}:#{bust[2]}",
        :pciBusId => "#{bust[1]}",
        :pciSubId => "#{bust[2]}",
        :category => "#{bust[3]}",
        :categoryId => "#{bust[4]}",
        :deviceName => "#{bust[5]}",
        :vendorId => "#{bust[6]}",
        :deviceId => "#{bust[7]}",
        :revision => "#{bust[9]}"
      }
    end
    return busDeviceMap
  end
  return false
end

##
# Validate the devices that can be used
##
def checkValidDevices(pciBusIds)
  ioDeviceMap=findBusIoDevices
  if pciBusIds != ""
    for ios in pciBusIds.split(/,/)
      if ioDeviceMap[ios]
        map=ioDeviceMap[ios]
        puts("Valid device on PCI bus #{ios}: #{map[:pciId]}, #{map[:deviceName]}, #{map[:vendorId]}:#{map[:deviceId]} ")
      else
        deviceListUsage
        abort("Device on PCI bus #{ios} is not a valid device")
      end
    end
  end
end

##
# Give back usage based on devices that exist
##
def deviceListUsage()
  ioDeviceMap=findBusIoDevices
  if ioDeviceMap != ""
    keys=[]
    ioDeviceMap.each_key do |key|
      keys.push(key)
      map=ioDeviceMap[key]
      puts("pcibusid: #{key} - device: #{map[:deviceName]} [#{map[:vendorId]}:#{map[:deviceId]}]")
    end
    line="#{keys.shift}"
    if keys.length != 0
      line = line + ",(" + keys.join(",") + ")"
    end
    puts("Usage: vagrant --pcibusid=#{line} <command>")
  else
    puts("No Sandisk Mass Storage Controller Found to pass through, aborting")
  end
end

opts = GetoptLong.new(
  [ '--pcibusid', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--box', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--force', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--halt-after-base-provisioning', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--halt-before-testing', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--skip-iomodule-check', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--provision', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--debug', GetoptLong::OPTIONAL_ARGUMENT ]
)

# need to build an option list from this though...
boxParam="generic/ubuntu1904"
boxParam="generic/opensuse15"
boxParam='archlinux/archlinux'
boxParam='fedora/31-cloud-base'
boxParam='generic/debian10'
haltAfterBaseProvisioning=false
haltBeforeTesting=false
skipSelection=true
skipIomoduleCheck=false
pciBusIds=''

for arg in ARGV
  case arg
  when 'up'
      skipSelection=false
      checkStatus=true
  end
end

opts.each do |opt, arg|
  case opt
  when '--box'
    boxParam=arg
  when '--halt-after-base-provisioning'
    haltAfterBaseProvisioning=true
  when '--halt-before-testing'
    haltBeforeTesting=true
  when '--pcibusid'
    pciBusIds=arg
  when '--skip-iomodule-check'
    skipIomoduleCheck=true
  end
end

if checkStatus == true
  status=checkVmStatus(boxParam)
end
if pciBusIds == "" && skipSelection == false
  deviceListUsage
  exit(1)
elsif pciBusIds != ""
  checkValidDevices(pciBusIds)
end

if ! skipIomoduleCheck && checkIoModule
  abort("There seems to be an iomemory module loaded: #{checkIoModule}, aborting")
# else
#  abort("testing!")
end

cpus = 8
memory = 8192
box = "#{boxParam}"
hostname = "fio.local"

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.host_name = hostname

  config.vm.provider :libvirt do |lv, override|
    lv.cpus = cpus
    lv.memory = memory
    # Support for more dynamic things...
    for ios in pciBusIds.split(/,/)
       lv.pci :bus => "0x#{ios}", :slot => '0x00', :function => '0x0'
    end
    # lv.pci :bus => '0x06', :slot => '0x00', :function => '0x0'
    if #{box}.match(/suse/i)
      lv.disk_bus = "sata"
    end
    if #{box}.match(/archlinux/i)
      lv.disk_bus = "virtio"
      # puts "With arch you have to run 'vagrant provision' after failure"
    end
  end
  config.vm.provision "file", source: "../envfile", destination: "envfile"
  config.vm.provision "file", source: "scripts/local_envs.sh", destination: "local_envs.sh"
  config.vm.provision "shell", path: "scripts/pre_prep.sh"
  config.vm.provision "shell", path: "scripts/prep_host.sh"
  config.vm.provision :reload
  if not haltAfterBaseProvisioning
    config.vm.provision "shell", path: "scripts/setup_module.sh"
    config.vm.provision "shell", path: "scripts/build_package.sh"
    # test package install?
    config.vm.provision "shell", path: "scripts/install_fio_tools.sh"
    if not haltBeforeTesting
      config.vm.provision "shell", path: "scripts/setup_filesystem.sh"
      config.vm.provision "shell", path: "scripts/test_tgz.sh"
      config.vm.provision "shell", path: "scripts/test_page_cache.sh"
      config.vm.provision "shell", path: "scripts/test_fio.sh"
      config.vm.provision "shell", path: "scripts/remove_module.sh"
      config.vm.provision "shell", path: "scripts/scrape_errors.sh"
    end
  end
end
